src/Entity/Booking.php
<?php

namespace App\Entity;

use App\Repository\BookingRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=BookingRepository::class)
 * @ORM\HasLifeCycleCallbacks
 */
class Booking
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity=User::class)
     * @ORM\JoinColumn(nullable=false)
     */
    private $booker;

    /**
     * @ORM\ManyToOne(targetEntity=Annonce::class)
     * @ORM\JoinColumn(nullable=false)
     */
    private $bookingAnnonce;

    /**
     * @ORM\Column(type="datetime")
     * @Assert\Type("\DateTimeInterface")
     * @Assert\NotBlank(message="La date de début ne peut pas être vide.")
     * @Assert\GreaterThanOrEqual("today", message="La date de début doit être supérieure ou égale à aujourd'hui.")
     * @Assert\LessThan(propertyPath="endDate", message="La date de début doit être inférieure à la date de fin.")
     */
    private $startDate;

    /**
     * @ORM\Column(type="datetime")
     * @Assert\Type("\DateTimeInterface")
     * @Assert\GreaterThan(propertyPath="startDate", message="La date de fin doit être supérieure à la date de début.")
     * @Assert\LessThanOrEqual("next year", message="La date selectionnés doit être cette année.")
     */
    private $endDate;
    /**
     * @ORM\Column(type="float")
     */
    private $amount;

    /**
     * @ORM\Column(type="datetime_immutable")
     */
    private $createdAt;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $comment;

    /**
     * Permet de générer la date de création, Calculer le montant avant même de persister l'entité
     * @ORM\PrePersist
     */
    public function prePersist(): void
    {
        if(empty($this->createdAt)) {
            $this->createdAt = new \DateTimeImmutable();
        }
        if(empty($this->amount)){
            $this->amount = $this->bookingAnnonce->getPrice() * $this->getDuration();
        }
    }

    //Connaitre si l'ppartement est reservable
    public function isBookableDates(){
            if (!$this->bookingAnnonce) {
            throw new \LogicException("Aucune annonce liée à cette réservation.");
        }

        $unavailableDays = $this->bookingAnnonce->getNotAvailableDays();
        $bookingDays = $this->getDays();

        foreach ($bookingDays as $day) {
            if (in_array($day->format('Y-m-d'), $unavailableDays)) {
                return false;
            }
        }

        return true;

    }

    public function getDays() : array{
        $days = [];
        $mysreservationDays = range(
            $this->startDate->getTimestamp(),
            $this->endDate->getTimestamp(),
            24*60*60 // 24 heures en secondes   
        );
        $days = array_map(function ($dayTimestamp) {
            return new \DateTime(date('Y-m-d', $dayTimestamp));
        }, $mysreservationDays);
        return $days;
    }

    public function getDuration(): int
    {
        return $this->startDate->diff($this->endDate)->days;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getBooker(): ?User
    {
        return $this->booker;
    }

    public function setBooker(?User $booker): self
    {
        $this->booker = $booker;

        return $this;
    }

    public function getBookingAnnonce(): ?Annonce
    {
        return $this->bookingAnnonce;
    }

    public function setBookingAnnonce(?Annonce $bookingAnnonce): self
    {
        $this->bookingAnnonce = $bookingAnnonce;

        return $this;
    }

    public function getStartDate(): ?\DateTimeInterface
    {
        return $this->startDate;
    }

    public function setStartDate(\DateTimeInterface $startDate): self
    {
        $this->startDate = $startDate;

        return $this;
    }

    public function getEndDate(): ?\DateTimeInterface
    {
        return $this->endDate;
    }

    public function setEndDate(\DateTimeInterface $endDate): self
    {
        $this->endDate = $endDate;

        return $this;
    }

    public function getAmount(): ?float
    {
        return $this->amount;
    }

    public function setAmount(float $amount): self
    {
        $this->amount = $amount;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeImmutable $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getComment(): ?string
    {
        return $this->comment;
    }

    public function setComment(?string $comment): self
    {
        $this->comment = $comment;

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use Cocur\Slugify\Slugify;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\UserRepository;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @ORM\HasLifecycleCallbacks
 * @UniqueEntity(
 *      fields = { "email" }, 
 *      message = "Un compte lié à ce mail existe déjà. Cliquez ici pour recuperer votre compte"
 * )
 * @method string getUserIdentifier()
 */
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="Veuillez rensigner votre prenom")
     */
    private $firstName;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="Veuillez renseigner votre nom de famille")
     */
    private $lastName;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Email(message="Veuillez renseigner un email valide")
     */
    private $email;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Url(message="Url non valide")
     */
    private $picture;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $hash;
    /**
     * @Assert\EqualTo(propertyPath="hash", message="Le mot de passe et la confirmation ne correspondent pas")
     */
    public $passwordConfirm;
    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length(
     *  min = 10,
     * minMessage="Introduction trop court"
     * )
     */
    private $introduction;

    /**
     * @ORM\Column(type="text")
     * @Assert\Length(
     *  min = 80,
     * minMessage="Vous devez avoir au moins 80 cartactère dans la description"
     * )
     */
    private $description;


    /**
     * @ORM\Column(type="string", length=255)
     */
    private $slug;

    /**
     * @ORM\OneToMany(targetEntity=Annonce::class, mappedBy="author")
     */
    private $annonces;

    /**
     * @ORM\ManyToMany(targetEntity=Role::class, mappedBy="users")
     */
    private $userRoles;


    #[ORM\OneToMany(mappedBy: 'agent', targetEntity: AppCall::class, cascade: ['persist', 'remove'])]
    private Collection $calls;

    public function __construct()
    {
        $this->annonces = new ArrayCollection();
        $this->userRoles = new ArrayCollection();
        $this->calls = new ArrayCollection();
    }
    /**
     * Permet d'initialiser le slug d'un utilisateur
     * @ORM\PrePersist
     * @ORM\PreUpdate
     * @return void
     */
    public function intitializeSlug() : void
    {
        if(empty($this ->slug)){
            $slugify = new Slugify();
            $this->slug = $slugify->slugify($this->getFirstName() . ' ' . $this->getLastName());
        }
    }

    public function getFullName() : ?String {
        return "{$this->getFirstName()} {$this->getLastName()}";
    }
    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFirstName(): ?string
    {
        return $this->firstName;
    }

    public function setFirstName(string $firstName): self
    {
        $this->firstName = $firstName;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->lastName;
    }

    public function setLastName(string $lastName): self
    {
        $this->lastName = $lastName;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getPicture(): ?string
    {
        return $this->picture;
    }

    public function setPicture(string $picture): self
    {
        $this->picture = $picture;

        return $this;
    }

    public function getHash(): ?string
    {
        return $this->hash;
    }

    public function setHash(string $hash): self
    {
        $this->hash = $hash;

        return $this;
    }

    public function getIntroduction(): ?string
    {
        return $this->introduction;
    }

    public function setIntroduction(string $introduction): self
    {
        $this->introduction = $introduction;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    /**
     * @return Collection<int, Annonce>
     */
    public function getAnnonces(): Collection
    {
        return $this->annonces;
    }

    public function addAnnonce(Annonce $annonce): self
    {
        if (!$this->annonces->contains($annonce)) {
            $this->annonces[] = $annonce;
            $annonce->setAuthor($this);
        }

        return $this;
    }

    public function removeAnnonce(Annonce $annonce): self
    {
        if ($this->annonces->removeElement($annonce)) {
            // set the owning side to null (unless already changed)
            if ($annonce->getAuthor() === $this) {
                $annonce->setAuthor(null);
            }
        }

        return $this;
    }

    public function getRoles()
    {
        
        $roles = $this->userRoles->map(function($role) {
            return $role->getTitle();
        })->toArray();
        $roles[] = 'ROLE_USER'; // On ajoute le rôle par défaut
        return $roles;
    }

    public function getPassword() : String
    {
        return $this->hash;
    }

    public function getSalt()
    {
        // TODO: Implement getSalt() method.
    }

    public function eraseCredentials()
    {
        // TODO: Implement eraseCredentials() method.
    }

    public function getUsername() : String
    {
        return $this->email;
    }

    public function getUserIdentifier(): string
    {
        return $this->email; // ou autre champ unique d’identification
    }

    public function __call($name, $arguments)
    {
        // TODO: Implement @method string getUserIdentifier()
    }

    /**
     * @return Collection<int, Role>
     */
    public function getUserRoles(): Collection
    {
        return $this->userRoles;
    }

    public function addUserRole(Role $userRole): self
    {
        if (!$this->userRoles->contains($userRole)) {
            $this->userRoles[] = $userRole;
            $userRole->addUser($this);
        }

        return $this;
    }

    public function removeUserRole(Role $userRole): self
    {
        if ($this->userRoles->removeElement($userRole)) {
            $userRole->removeUser($this);
        }

        return $this;
    }

    /**
     * @return Collection<int, Call>
     */
    public function getCalls(): Collection
    {
        return $this->calls;
    }

    public function addCall(AppCall $call): self
    {
        if (!$this->calls->contains($call)) {
            $this->calls[] = $call;
            $call->setAgent($this);
        }
        return $this;
    }

    public function removeCall(AppCall $call): self
    {
        if ($this->calls->removeElement($call)) {
            if ($call->getAgent() === $this) {
                $call->setAgent(null);
            }
        }
        return $this;
    }
}

src/Form/BookingType.php
<?php

namespace App\Form;

use App\Entity\Booking;
use PharIo\Manifest\Application;

use App\Form\ApplicationType;
use App\Form\DataTransformers\FrenchToDateTimeTransformer;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class BookingType extends ApplicationType
{
    private $transformer;
    public function __construct(FrenchToDateTimeTransformer $tranformer)
    {
        $this->transformer = $tranformer;
    }
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('startDate',
            TextType::class, 
            $this->getConfiguration("Date de début", "La date à laquelle vous souhaitez commencer votre réservation",
            ))
            ->add('endDate', 
            TextType::class,
            $this->getConfiguration("Date de fin", "La date à laquelle vous souhaitez terminer votre réservation",
            ))
            ->add('comment',
            TextareaType::class,
            $this->getConfiguration("Commentaire", "Si vous avez des questions, n'hésitez pas à les poser ici",
            ['required' => false, 'attr' => ['rows' => 5]])
            )
        ;
        $builder->get('startDate')->addModelTransformer($this->transformer);
        $builder->get('endDate')->addModelTransformer($this->transformer);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Booking::class,
        ]);
    }
}

src/Controller/BookingController.php
<?php

namespace App\Controller;

use App\Entity\Annonce;
use App\Entity\Booking;
use App\Form\BookingType;
use App\Repository\BookingRepository;
use Doctrine\ORM\EntityManagerInterface;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class BookingController extends AbstractController
{
    #[Route('/annonces/{slug}/book', name: 'booking_create')]
    #[IsGranted('ROLE_USER', message: 'Vous devez être connecté pour réserver une annonce')]
    public function book(Annonce $annonce, Request $request, EntityManagerInterface $manager): Response
    {
        $booking =  new Booking();
        $form = $this->createForm(BookingType::class, $booking);
        $form->handleRequest($request);
        if($form->isSubmitted() && $form->isValid()){
            $booking->setBooker($this->getUser())
                    ->setBookingAnnonce($annonce);
            if (!$booking->isBookableDates()) {
                $this->addFlash('warning', 'Les dates sélectionnées ne sont pas disponibles.');
                #return $this->redirectToRoute('annonce_show', ['slug' => $annonce->getSlug()]);
            }
            else{
                
                $manager->persist($booking);
                $manager->flush();
                return $this->redirectToRoute('booking_show', ['id' => $booking->getId(), 'success' => true]);
            }
            
        }
        return $this->render('booking/book.html.twig', [
            'annonce' => $annonce,
            'form' => $form->createView(),
        ]);
    }
    #[Route('booking/{id}', name :'booking_show')]
    #[IsGranted('ROLE_USER')]
    public function show(Booking $booking) : Response
    {
        return $this->render('booking/show.html.twig', [
            'booking' => $booking
        ]);
    }
}

templates/booking/book.html.twig
{% extends 'base.html.twig' %}

{% block title %}Reservation pour {{annonce.tittle}}{% endblock %}
{% block stylesheets %}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.10.0/css/bootstrap-datepicker.min.css" integrity="sha512-34s5cpvaNG3BknEWSuOncX28vz97bRI59UnVtEEpFX536A7BtZSJHsDyFoCl8S7Dt2TPzcrCEoHBGeM4SUBDBw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
{% endblock %}
{% block body %}
    <div class="container mt-5">
        <div class="row d-flex justify-content-center">
            <div class="col-md-5">
                <div class="card p-3 py-4">
                    <div class="text-center mt-3">
                        <h5 class="mt-2 mb-0"> Reservation de l'annonce <span>{{annonce.tittle}}</span>  </h5>
                        <hr>
                        <div class="px-4 mt-1">
                            {{form_start(form)}}
                                <div class="form-group">
                                    {{form_row(form.startDate, {'attr': {'class': 'form-control'}})}}
                                </div>  
                                <div class="form-group">
                                    {{form_row(form.endDate, {'attr': {'class': 'form-control'}})}}
                                </div>
                                <div class="form-group">
                                    {{form_row(form.comment)}}
                                </div>
                                <div class="row">
                                    <div class="col-md-6">
                                        <h5 class="mt-2 mb-0">
                                            Montant total : <strong id="amount"></strong> &euro;
                                        </h5>
                                    </div>
                                    <div class="col-md-6">
                                        <h5 class="mt-2 mb-0">
                                            Nombre de jours : <strong id="days">... </strong> days
                                        </h5>
                                    </div>
                                </div>
                                <div class="buttons mt-4 mb-3">
                                    <button type="submit" class="btn btn-outline-primary px-4">Enregistrer</button>
                                    <button type="reset" class="btn btn-primary px-4 ms-3">Reinitialiser</button>
                                </div>
                            {{form_end(form)}}
                        </div>
                    </div>        
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block jsperso %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.10.0/js/bootstrap-datepicker.min.js" integrity="sha512-LsnSViqQyaXpD4mBBdRYeP6sRwJiJveh2ZIbW41EBrNmKxgr/LFZIiWT6yr+nycvhvauz8c2nYMhrP80YhG7Cw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script>
        $(document).ready(function(){
            $('#booking_startDate, #booking_endDate').datepicker({
                    format: 'dd/mm/yyyy',
                    autoclose: true,
                    todayHighlight: true,
                    datesDisabled: [
                        {% for day in annonce.notAvailableDays %}
                            "{{ day.format('d/m/Y')}}",
                        {% endfor %}
                    ],
                    startDate: new Date(),
            });
            $('#booking_startDate, #booking_endDate').on('change', calculateAmount)
        });
        function calculateAmount(){
            const DAY_TIME = 24 * 60 * 60 * 1000;
            let startStr = $('#booking_startDate').val();
            let endStr = $('#booking_endDate').val();
            const startDate = new Date(startStr.replace(/(\d+)\/(\d+)\/(\d{4})/, "$3-$2-$1"));
            const endDate = new Date(endStr.replace(/(\d+)\/(\d+)\/(\d{4})/, "$3-$2-$1"));
            if(startDate && endDate && startDate < endDate){
                const interval = endDate.getTime() - startDate.getTime();
                const days = interval / DAY_TIME;
                const amount = days * {{ annonce.price }}
                $('#days').text(days);
                $('#amount').text(amount.toLocaleString('fr-FR', {minimumFractionDigits: 2, maximumFractionDigits: 2}));
            }
        }
    </script>
{% endblock %}

templates/booking/show.html.twig
{% extends "base.html.twig" %}
{% set annonce = booking.bookingAnnonce %}
{% set author = annonce.author %}
{% block title %}Reservation sur {{ annonce.tittle}}{% endblock %}
{% block body %}
    <div class="container mt-5">
        <h5 class="mt-2 mb-0 text-center"> Reservation de l'annonce <span>{{annonce.tittle}}</span> </h5>
        <hr>
        {% if app.request.query.get('success') %}
            <div class="alert alert-success">
                <h4 class="alert-heading text-center">Bravo !</h4>
                <p>Votre reservation auprè de <strong><a href=" {{ path('user_show', {'slug' : author.slug})}}">{{ author.fullName}}</a></strong>
                pour l'annonce <strong><a href="{{ path('annonce_show', {'slug' : annonce.slug})}}">{{ annonce.tittle}}</a></strong> a bien été prise en compte.</p>
                </p>
            </div>
        {% endif %}
        
        <div class="row d-flex justify-content-center">
            <div class="col-md-5">
                <div class="text-center mt-3">
                    <h5 class="mt-2 mb-0"> Reservation (n° {{ booking.id}}) </h5>
                    <hr>
                    <div class="alert alert-light px-4 mt-1">
                        <dl class="row">
                            <dt class="col-md-4">Numéro de la résérvation : </dt>
                            <dd class="col-md-8">{{ booking.id}}</dd>
                            <dt class="col-md-4">Date de début : </dt>
                            <dd class="col-md-8">{{ booking.startDate | date('d/m/Y')}}</dd>
                            <dt class="col-md-4">Date de départ prévu : </dt>
                            <dd class="col-md-8">{{ booking.endDate | date('d/m/Y')}}</dd>
                            <dt class="col-md-4">Durée de la réservation : </dt>
                            <dd class="col-md-8">{{ booking.duration}}</dd>
                            <dt class="col-md-4">Montant total : </dt>
                            <dd class="col-md-8">{{ booking.amount}} &euro;</dd>
                            <dt class="col-md-4">Commenatire : </dt>
                            <dd class="col-md-8">{{ booking.comment}}</dd>
                        </dl>
                    </div>
                    <h5 class="mt-2 mb-0"> Rôles </h5>
                    <hr>
                    <div class="alert alert-light px-4 mt-1">
                        <div class="row">
                            <div class="col-3">
                                <img src="{{ author.picture}}" alt="Avatar de {{ author.fullName}}" class="author author-medium">
                            </div>
                            <div class="col">
                                <a href="{{ path('user_show', {'slug' : author.slug})}}">{{ author.fullName}}</a>
                                <div>
                                    <span class="btn btn-dark btn-sm">{{ author.annonces | length}} annonces</span>
                                </div>
                            </div>
                        </div>
                        
                        {{ author.description | raw}}
                        <a href="{{ path('user_show', {'slug' : author.slug})}}" class="btn btn-dark"> Plus de détails sur {{ author.firstname}}</a>
                    </div>
                </div> 
            </div>
            <div class="col-md-7">
                <h5 class="mt-2 mb-0 text-center">Votre hébergement</h5>
                <hr>
                <div class="alert alert-light px-4 mt-1">
                        <h5 class="mt-2 mb-2">{{annonce.tittle}}</h5>
                        <img src="{{ annonce.converImage}}" alt="Image de {{ annonce.tittle}}" class="fluid">
                        
                        <div class="mt-3">
                            <p>{{annonce.content | raw}}</p>

                            <a href="{{path('annonce_show', {'slug' : annonce.slug})}}" class="btn btn-dark">Plus de détails</a>
                        </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}